name: Custom Tasmota Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        working-directory: tasmota
        run: pio run -e tasmota

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/tasmota/fir
